# Entries marked `if personal` are installed only on machines that opt in by
# creating the marker file below. Where it is absent those applications are
# provisioned outside Homebrew, so Homebrew must not try to own them.
#
# The path is fixed under $HOME rather than $XDG_CONFIG_HOME on purpose:
# `brew bundle` scrubs the environment before evaluating this file, so
# XDG_CONFIG_HOME arrives here as nil even when it is set. Honouring it on the
# writing side alone would put the marker where this check never looks.
personal = File.exist?(File.expand_path("~/.config/dotfiles/personal"))

tap "songmu/tap"
tap "modem-dev/tap"
brew "argocd"
brew "bat"
brew "btop"
brew "clang-format"
brew "curl"
brew "envchain"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "ghq"
brew "git"
brew "git-delta"
brew "gnu-sed"
brew "go"
brew "grep"
brew "helix"
brew "helm"
brew "herdr", start_service: true
brew "modem-dev/tap/hunk"
brew "ipcalc"
brew "jo"
brew "jq"
brew "jsonnet"
brew "k9s"
brew "kube-ps1"
brew "kubectx"
brew "kubeseal"
brew "kustomize"
brew "lazydocker"
brew "lazygit"
brew "lima"
brew "mas"
brew "mise"
brew "php"
brew "ripgrep"
brew "sheldon"
brew "starship"
brew "tig"
brew "tree"
brew "neovim"
brew "watch"
brew "wget"
brew "yq"
brew "zoxide"
brew "zsh"
brew "songmu/tap/blogsync"
cask "1password" if personal
cask "1password-cli"
cask "appcleaner"
cask "claude-code"
cask "firefox"
cask "font-hackgen"
cask "ghostty"
cask "git-credential-manager"
cask "gitify"
cask "google-chrome"
cask "gpg-suite"
cask "hammerspoon"
cask "karabiner-elements"
cask "notion"
cask "obsidian"
cask "postman"
cask "rancher"
cask "raycast"
cask "slack"
cask "the-unarchiver"
cask "visual-studio-code"
cask "wezterm"
