[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'psf/black'

