[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = "ctrlpvim/ctrlp.vim"

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'Lokaltog/vim-powerline'

[[plugins]]
repo = 'tpope/vim-obsession'

